name: macos-ci

on:
  schedule:
    # Every Monday at 3 am
    - cron: '0 3 * * 1'
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-11]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
    
    - name: Checkout HIV_malawi repository
      uses: actions/checkout@v2

    - name: Make sure Xcode 13.1 is used on macOS 11.6 as the default /Application/Xcode.app
      shell: bash
      run: |
        sudo mv /Applications/Xcode.app /Applications/Xcode.app-
        sudo ln -s /Applications/Xcode_13.1.app /Applications/Xcode.app
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      if: matrix.os == 'macos-11'

    - name: Install dependencies
      run: |
        brew install libomp open-mpi python@3.9 wget cmake ninja
   
    - name: Install BioDynaMo
      run: |
        cd ..
        git clone https://github.com/BioDynaMo/biodynamo.git
        cd biodynamo
        cmake -G Ninja \
          -Dparaview=off \
          -DCMAKE_BUILD_TYPE=Release \
          -B build
        cmake --build build --parallel --config Release

    - name: Build hiv_malawi and run small simulation
      run: |
        sed -i '' 's/uint64_t number_of_iterations = 60/uint64_t number_of_iterations = 3/g' src/sim-param.h
        . ../biodynamo/build/bin/thisbdm.sh
        cmake -G Ninja -B build
        cmake --build build --parallel --config Release
        ./build/hiv_malawi