name: ubuntu-ci

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Install BioDynaMo dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev libomp5 libomp-dev libnuma-dev freeglut3-dev \
          libreadline-dev libsqlite3-dev tk-dev python-openssl ninja-build
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.19.3/cmake-3.19.3-Linux-x86_64.sh
        chmod +x cmake-3.19.3-Linux-x86_64.sh
        sudo ./cmake-3.19.3-Linux-x86_64.sh --skip-license --prefix=/usr/local
   
    - name: Install BioDynaMo
      # working-directory: ./app
      run: |
        if [ ! -f "$HOME/.pyenv/bin/pyenv" ]; then
          curl https://pyenv.run | bash
        fi
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.1
        pyenv shell 3.9.1
        git clone https://github.com/BioDynaMo/biodynamo.git
        cd biodynamo
        pwd
    #     cmake -G Ninja \
    #       -Dparaview=off \
    #       -DCMAKE_BUILD_TYPE=Release \
    #       -B build
    #     cmake --build build --parallel --config Release
    #     . build/bin/thisbdm.sh

    - name: Checkout HIV_malawi repository
      uses: actions/checkout@v2

    cannot find BDM
    - name: Build HIV_malawi repository
      run: |
        sed -i 's/uint64_t number_of_iterations = 60/uint64_t number_of_iterations = 3/g' src/sim-param.h
        ls -a
        pwd
    #     cmake -G Ninja -B build
    #     cmake --build build --parallel --config Release
    #     ./build/hiv-malawi