name: ubuntu-ci

on:
  schedule:
    # Every day at 3 am
    - cron: '0 3 * * *'
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    
    - name: Checkout HIV_malawi repository
      uses: actions/checkout@v2
    
    - name: Install BioDynaMo dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev libomp5 libomp-dev libnuma-dev freeglut3-dev \
          libreadline-dev libsqlite3-dev tk-dev python-openssl ninja-build
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.19.3/cmake-3.19.3-Linux-x86_64.sh
        chmod +x cmake-3.19.3-Linux-x86_64.sh
        sudo ./cmake-3.19.3-Linux-x86_64.sh --skip-license --prefix=/usr/local
   
    - name: Install BioDynaMo
      run: |
        if [ ! -f "$HOME/.pyenv/bin/pyenv" ]; then
          curl https://pyenv.run | bash
        fi
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.1
        pyenv shell 3.9.1
        cd ..
        git clone https://github.com/BioDynaMo/biodynamo.git
        cd biodynamo
        cmake -G Ninja \
          -Dparaview=off \
          -DCMAKE_BUILD_TYPE=Release \
          -B build
        cmake --build build --parallel --config Release

    - name: Build hiv_malawi and run small simulation
      run: |
        sed -i 's/uint64_t number_of_iterations = 60/uint64_t number_of_iterations = 3/g' src/sim-param.h
        . ../biodynamo/build/bin/thisbdm.sh
        cmake -G Ninja -B build
        cmake --build build --parallel --config Release
        ./build/hiv_malawi